(function () {
  "use strict";

  var BANKS = Array.isArray(window.MOST_SIMULATOR_BANK_CONFIG) ? window.MOST_SIMULATOR_BANK_CONFIG : [];
  var BRL = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
  var PERCENT = new Intl.NumberFormat("pt-BR", { style: "percent", minimumFractionDigits: 2, maximumFractionDigits: 2 });
  var DATE = new Intl.DateTimeFormat("pt-BR");
  var EMPTY_USER = { goal: null, income: null, hasJointIncome: null, jointIncome: 0, commitments: 0, birthDate: null, downPayment: 0, useFgts: false, fgtsValue: 0, propertyValue: null, name: null, contactPreference: null, email: null, phone: null, marketingOptIn: false };
  var app = createState();

  var FLOW = {
    welcome: "goal", goal: "income", income: "joint_income_question",
    joint_income_question: function () { return app.user.hasJointIncome ? "joint_income" : "commitments"; },
    joint_income: "commitments", commitments: "birth_date", birth_date: "down_payment", down_payment: "fgts_question",
    fgts_question: function () { return app.user.useFgts ? "fgts_value" : afterFgts(); },
    fgts_value: afterFgts, property_value: "scenario_review", scenario_review: "name", name: "contact_preference",
    contact_preference: "contact", contact: "marketing", marketing: "calculating", calculating: "result", result: "scenario_exploration"
  };

  function createState() { return { current: "welcome", user: Object.assign({}, EMPTY_USER), results: [], answered: {} }; }
  function afterFgts() { return app.user.goal === "property_check" ? "property_value" : "scenario_review"; }
  function isNumber(value) { return typeof value === "number" && Number.isFinite(value); }
  function parseMoney(value) { var digits = String(value || "").replace(/\D/g, ""); return digits ? Number(digits) : 0; }
  function money(value) { return isNumber(value) ? BRL.format(value) : "Em configuração"; }

  function calculateAge(value, referenceDate) {
    var birth = new Date(value + "T00:00:00"); var today = referenceDate || new Date();
    if (!value || Number.isNaN(birth.getTime()) || birth > today) return null;
    var age = today.getFullYear() - birth.getFullYear();
    if (today.getMonth() < birth.getMonth() || (today.getMonth() === birth.getMonth() && today.getDate() < birth.getDate())) age -= 1;
    return age;
  }
  function getAvailableTerm(bank, age) {
    if (!isNumber(bank.maxTermMonths) || bank.maxTermMonths <= 0) return null;
    var term = bank.maxTermMonths;
    if (isNumber(bank.maxAgeAtEnd) && isNumber(age)) term = Math.min(term, Math.floor((bank.maxAgeAtEnd - age) * 12));
    return term > 0 ? term : null;
  }
  function getIncomeCapacity(income, commitments, ratio) { return isNumber(income) && isNumber(ratio) ? Math.max((income * ratio) - Math.max(commitments || 0, 0), 0) : 0; }
  function annualToMonthlyRate(rate) { return isNumber(rate) && rate >= 0 ? Math.pow(1 + rate, 1 / 12) - 1 : null; }
  function calculatePricePrincipal(payment, rate, term) { if (![payment, rate, term].every(isNumber) || term <= 0) return null; return rate === 0 ? payment * term : payment * (1 - Math.pow(1 + rate, -term)) / rate; }
  function calculateSacPrincipal(payment, rate, term) { return [payment, rate, term].every(isNumber) && term > 0 ? payment / ((1 / term) + rate) : null; }
  function calculateFirstPayment(principal, rate, term, system) { if (![principal, rate, term].every(isNumber) || term <= 0) return null; if (system === "SAC") return principal / term + principal * rate; return rate === 0 ? principal / term : principal * rate / (1 - Math.pow(1 + rate, -term)); }
  function calculateLastPayment(principal, rate, term, system) { return system === "SAC" ? principal / term + (principal / term) * rate : calculateFirstPayment(principal, rate, term, system); }
  function calculateRequiredIncome(payment, commitments, ratio) { return isNumber(payment) && isNumber(ratio) && ratio > 0 ? (payment + Math.max(commitments || 0, 0)) / ratio : null; }
  function calculateBuyingPower(capacity, entry, ltv) { if (![capacity, entry, ltv].every(isNumber) || ltv <= 0 || ltv > 1) return null; return Math.min(capacity + entry, ltv === 1 ? Infinity : entry / (1 - ltv)); }
  function validateBankConfig(bank) {
    if (!bank || bank.enabled !== true) return { valid: false, status: "unavailable" };
    var valid = [bank.annualRate, bank.maxLtv, bank.maxIncomeCommitment, bank.maxTermMonths].every(isNumber) && Boolean(bank.source && bank.sourceDate) && ["PRICE", "SAC"].indexOf(bank.amortizationSystem) >= 0;
    if (!valid) console.error("[Poder de Compra MOST] Instituição habilitada sem configuração completa:", bank.name || bank.id);
    return { valid: valid, status: valid ? "valid" : "config_error" };
  }
  function scenario() { return { totalIncome: (app.user.income || 0) + (app.user.hasJointIncome ? app.user.jointIncome || 0 : 0), commitments: app.user.commitments || 0, birthDate: app.user.birthDate, totalEntry: (app.user.downPayment || 0) + (app.user.useFgts ? app.user.fgtsValue || 0 : 0), propertyValue: app.user.propertyValue }; }
  function simulateBank(bank, data) {
    var config = validateBankConfig(bank); if (!config.valid) return { bank: bank, status: config.status, message: "Parâmetros em validação." };
    var term = getAvailableTerm(bank, calculateAge(data.birthDate)); var rate = annualToMonthlyRate(bank.annualRate); var payment = getIncomeCapacity(data.totalIncome, data.commitments, bank.maxIncomeCommitment);
    if (!term || !isNumber(rate) || payment <= 0) return incompatible(bank);
    var capacity = bank.amortizationSystem === "SAC" ? calculateSacPrincipal(payment, rate, term) : calculatePricePrincipal(payment, rate, term);
    var power = calculateBuyingPower(capacity, data.totalEntry, bank.maxLtv); if (!isNumber(capacity) || capacity <= 0 || !isNumber(power)) return incompatible(bank);
    var principal = data.propertyValue ? Math.min(capacity, Math.max(data.propertyValue - data.totalEntry, 0), data.propertyValue * bank.maxLtv) : capacity;
    var first = calculateFirstPayment(principal, rate, term, bank.amortizationSystem);
    return { bank: bank, status: "valid", financingCapacity: capacity, buyingPower: power, firstPayment: first, lastPayment: calculateLastPayment(principal, rate, term, bank.amortizationSystem), requiredIncome: calculateRequiredIncome(first, data.commitments, bank.maxIncomeCommitment), termMonths: term };
  }
  function incompatible(bank) { return { bank: bank, status: "incompatible", message: "Este cenário ficou fora dos parâmetros considerados nesta simulação." }; }
  function simulateAllBanks(banks, data) { return banks.map(function (bank) { return simulateBank(bank, data); }); }

  function node(tag, className, text) { var item = document.createElement(tag); if (className) item.className = className; if (text !== undefined) item.textContent = text; return item; }
  function mount() {
    document.getElementById("most-simulator").innerHTML = "<div class=\"b-container\"><div class=\"most-conversation-heading\"><div><span class=\"most-simulator-eyebrow\">Assistente MOST</span><h2>Seu cenário, uma pergunta por vez.</h2></div><button id=\"scenario-toggle\" type=\"button\" class=\"most-scenario-toggle\" aria-expanded=\"false\"><i class=\"bi bi-sliders\"></i> Ver meu cenário</button></div><div class=\"most-conversation-layout\"><section class=\"most-conversation-card\" aria-label=\"Conversa com a Most\"><div id=\"conversation-feed\" class=\"most-conversation-feed\" aria-live=\"polite\"></div><div id=\"conversation-action\" class=\"most-conversation-action\"></div></section><aside id=\"scenario-panel\" class=\"most-scenario-panel\"><div class=\"most-scenario-panel-heading\"><div><span class=\"most-simulator-eyebrow\">Resumo</span><h3>Seu cenário</h3></div><button id=\"scenario-close\" class=\"most-icon-button\" type=\"button\" aria-label=\"Fechar resumo\"><i class=\"bi bi-x-lg\"></i></button></div><div id=\"scenario-content\" class=\"most-scenario-panel-content\"></div></aside></div><section id=\"result\" class=\"most-simulator-result\" hidden><span class=\"most-simulator-eyebrow\">Seu resultado</span><h2>Poder de compra estimado</h2><div class=\"most-result-overview\"><div class=\"most-result-primary\"><span>Poder de compra estimado</span><strong id=\"result-value\"></strong><p id=\"result-copy\"></p></div><dl id=\"result-summary\" class=\"most-result-summary\"></dl></div><div id=\"result-highlights\" class=\"most-result-highlights\"></div><div id=\"property-comparison\" class=\"most-result-property\" hidden></div><section class=\"most-result-comparison\"><h3>Comparação entre instituições</h3><p id=\"comparison-copy\"></p><div id=\"bank-grid\" class=\"most-bank-result-grid\"></div></section><section class=\"most-result-next\"><div><span class=\"most-simulator-eyebrow\">Próximo passo</span><h3>Quer transformar essa estimativa em uma análise mais aprofundada do seu cenário?</h3><p>A Most pode ajudar a entender as possibilidades e organizar os próximos passos da operação.</p></div><a href=\"contato.html\" class=\"btn-cta-primary\"><span class=\"btn-text\">Falar com a Most</span><i class=\"bi bi-arrow-right-circle-fill btn-icon-primary\"></i></a></section></section></div>";
  }
  function message(role, text) { var article = node("article", "most-message most-message-" + role); if (role === "assistant") article.appendChild(node("span", "most-message-author", "MOST")); article.appendChild(node("p", "", text)); document.getElementById("conversation-feed").appendChild(article); requestAnimationFrame(function () { article.scrollIntoView({ behavior: "smooth", block: "nearest" }); }); }
  function clearAction() { document.getElementById("conversation-action").replaceChildren(); }
  function button(label, value, handler, secondary) { var item = node("button", secondary ? "most-action-secondary" : "most-quick-reply", label); item.type = "button"; item.dataset.value = value; item.addEventListener("click", handler); return item; }
  function replies(options, callback) { clearAction(); var wrap = node("div", "most-quick-replies"); options.forEach(function (option) { wrap.appendChild(button(option[0], option[1], function () { callback(option[1], option[0]); })); }); document.getElementById("conversation-action").appendChild(wrap); wrap.querySelector("button").focus({ preventScroll: true }); }
  function input(options, callback) {
    clearAction(); var form = node("form", "most-conversation-input"); form.noValidate = true; var label = node("label", "visually-hidden", options.label); var field = node("input"); field.id = "conversation-input"; field.type = options.type || "text"; field.placeholder = options.placeholder || ""; field.autocomplete = options.autocomplete || "off"; field.inputMode = options.mode || "text"; label.htmlFor = field.id; var submit = node("button", "most-submit-button", "Continuar"); submit.type = "submit"; var error = node("span", "most-conversation-error"); error.setAttribute("role", "alert"); form.append(label, field, submit, error); form.addEventListener("submit", function (event) { event.preventDefault(); var problem = callback(field.value); if (problem) { error.textContent = problem; field.setAttribute("aria-invalid", "true"); field.focus(); } }); document.getElementById("conversation-action").appendChild(form); setTimeout(function () { field.focus({ preventScroll: true }); }, 30);
  }
  function answer(text) { message("user", text); }
  function next() { var target = FLOW[app.current]; go(typeof target === "function" ? target() : target); }
  function go(state) { if (!state) return; app.current = state; renderState(state); }
  function acceptMoney(raw, key, allowZero) { var value = parseMoney(raw); if ((!allowZero && value <= 0) || value > 999999999) return "Informe um valor válido" + (allowZero ? "." : " maior que zero."); app.user[key] = value; app.answered[key] = true; answer(money(value)); updatePanel(); next(); return ""; }
  function ask(text) { message("assistant", text); }

  function renderState(state) {
    if (state === "welcome") { ask("Olá. Eu sou a MOST e vou ajudar você a entender seu poder de compra estimado, passo a passo."); return replies([["Vamos começar", "start"]], function () { answer("Vamos começar"); next(); }); }
    if (state === "goal") { ask("Vamos descobrir quanto imóvel cabe no seu momento?"); return replies([["Quanto eu posso comprar", "buying_power"], ["Já tenho um imóvel em mente", "property_check"]], function (value, label) { app.user.goal = value; app.answered.goal = true; answer(label); updatePanel(); next(); }); }
    if (state === "income") { ask("Qual é sua renda bruta mensal?"); return input({ label: "Renda bruta mensal", placeholder: "R$ 0", mode: "numeric" }, function (value) { return acceptMoney(value, "income", false); }); }
    if (state === "joint_income_question") { ask("Você pretende compor renda com outra pessoa?"); return replies([["Sim", "yes"], ["Não", "no"]], function (value, label) { app.user.hasJointIncome = value === "yes"; app.user.jointIncome = app.user.hasJointIncome ? app.user.jointIncome : 0; app.answered.hasJointIncome = true; answer(label); updatePanel(); next(); }); }
    if (state === "joint_income") { ask("Qual é a renda bruta mensal dessa pessoa?"); return input({ label: "Renda da outra pessoa", placeholder: "R$ 0", mode: "numeric" }, function (value) { return acceptMoney(value, "jointIncome", false); }); }
    if (state === "commitments") { ask("Quanto da sua renda já está comprometido mensalmente?"); ask("Considere parcelas de empréstimos, financiamentos e outros compromissos recorrentes relevantes."); return input({ label: "Compromissos mensais", placeholder: "R$ 0", mode: "numeric" }, function (value) { var problem = acceptMoney(value, "commitments", true); var total = (app.user.income || 0) + (app.user.jointIncome || 0); if (!problem && total && app.user.commitments / total >= 0.2) ask("Entendi. Seus compromissos atuais serão considerados porque eles podem reduzir a parcela disponível para um novo financiamento."); return problem; }); }
    if (state === "birth_date") { ask("Qual sua data de nascimento?"); ask("Essa informação ajuda a calcular os prazos que podem ser considerados na simulação. Não precisamos do seu CPF nesta etapa."); return input({ label: "Data de nascimento", type: "date", autocomplete: "bday" }, function (value) { var age = calculateAge(value); if (age === null || age < 18 || age > 120) return "Informe uma data de nascimento válida."; app.user.birthDate = value; app.answered.birthDate = true; answer(DATE.format(new Date(value + "T00:00:00"))); updatePanel(); next(); return ""; }); }
    if (state === "down_payment") { ask("Quanto você tem disponível para entrada?"); return input({ label: "Entrada", placeholder: "R$ 0", mode: "numeric" }, function (value) { var problem = acceptMoney(value, "downPayment", true); if (!problem) ask("A entrada influencia tanto o valor financiado quanto o valor total do imóvel que seu cenário pode alcançar."); return problem; }); }
    if (state === "fgts_question") { ask("Pretende considerar FGTS como parte da entrada?"); return replies([["Sim", "yes"], ["Não", "no"]], function (value, label) { app.user.useFgts = value === "yes"; app.user.fgtsValue = app.user.useFgts ? app.user.fgtsValue : 0; app.answered.useFgts = true; answer(label); updatePanel(); next(); }); }
    if (state === "fgts_value") { ask("Qual valor você gostaria de considerar?"); ask("A utilização efetiva do FGTS depende das regras aplicáveis à operação."); return input({ label: "Valor do FGTS", placeholder: "R$ 0", mode: "numeric" }, function (value) { return acceptMoney(value, "fgtsValue", true); }); }
    if (state === "property_value") { ask("Qual é o valor do imóvel que você está considerando?"); return input({ label: "Valor do imóvel", placeholder: "R$ 0", mode: "numeric" }, function (value) { return acceptMoney(value, "propertyValue", false); }); }
    if (state === "scenario_review") { ask("Perfeito. Já tenho o necessário para montar seu cenário."); return review(); }
    if (state === "name") { ask("Antes de abrir sua comparação completa, como posso te chamar?"); return input({ label: "Nome", placeholder: "Seu nome", autocomplete: "name" }, function (value) { var name = String(value || "").trim(); if (name.length < 2) return "Informe seu nome."; app.user.name = name.slice(0, 80); answer(app.user.name); next(); return ""; }); }
    if (state === "contact_preference") { ask("Prazer, " + app.user.name + ". Por onde você prefere continuar essa conversa depois?"); return replies([["E-mail", "email"], ["WhatsApp", "whatsapp"]], function (value, label) { app.user.contactPreference = value; answer(label); next(); }); }
    if (state === "contact") return contact();
    if (state === "marketing") { ask("Quer receber também análises e novidades da Most sobre crédito e mercado imobiliário?"); replies([["Quero receber", "yes"], ["Agora não", "no"]], function (value, label) { app.user.marketingOptIn = value === "yes"; answer(label); next(); }); privacy(); return; }
    if (state === "calculating") { clearAction(); ask("Pronto, " + app.user.name + ". Vou comparar seu cenário com os parâmetros disponíveis na simulação."); var status = node("div", "most-calculating"); ["Cenário financeiro", "Entrada", "Prazo", "Parâmetros disponíveis"].forEach(function (text) { status.appendChild(node("span", "", "✓ " + text)); }); document.getElementById("conversation-action").appendChild(status); return setTimeout(next, 550); }
    if (state === "result") { clearAction(); app.results = simulateAllBanks(BANKS, scenario()); ask("Pronto, " + app.user.name + "."); renderResults(); return next(); }
    if (state === "scenario_exploration") return exploration();
  }

  function contact() { var email = app.user.contactPreference === "email"; ask(email ? "Qual é o seu melhor e-mail?" : "Qual é o seu número de WhatsApp?"); input({ label: email ? "E-mail" : "WhatsApp", type: email ? "email" : "tel", placeholder: email ? "voce@exemplo.com.br" : "(00) 00000-0000", autocomplete: email ? "email" : "tel", mode: email ? "email" : "tel" }, function (value) { var clean = String(value || "").trim(); if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean)) return "Informe um e-mail válido."; if (!email && clean.replace(/\D/g, "").length < 10) return "Informe um WhatsApp válido com DDD."; app.user[email ? "email" : "phone"] = clean; answer(clean); next(); return ""; }); }
  function privacy() { var note = node("p", "most-privacy-note"); note.append(document.createTextNode("Seus dados são utilizados nesta experiência e para permitir a continuidade do atendimento solicitado. ")); var link = node("a", "", "Política de Privacidade"); link.href = "politica-de-privacidade.html"; note.appendChild(link); document.getElementById("conversation-action").appendChild(note); }
  function rows() { var output = []; if (app.answered.goal) output.push(["goal", "Objetivo", app.user.goal === "property_check" ? "Imóvel específico" : "Poder de compra"]); if (app.answered.income) output.push(["income", "Renda", money(app.user.income)]); if (app.user.hasJointIncome && app.answered.jointIncome) output.push(["joint_income", "Renda conjunta", money(app.user.jointIncome)]); if (app.answered.commitments) output.push(["commitments", "Compromissos", money(app.user.commitments)]); if (app.answered.birthDate) output.push(["birth_date", "Nascimento", DATE.format(new Date(app.user.birthDate + "T00:00:00"))]); if (app.answered.downPayment) output.push(["down_payment", "Entrada", money(app.user.downPayment)]); if (app.user.useFgts && app.answered.fgtsValue) output.push(["fgts_value", "FGTS", money(app.user.fgtsValue)]); if (app.answered.propertyValue) output.push(["property_value", "Imóvel desejado", money(app.user.propertyValue)]); return output; }
  function updatePanel() { var content = document.getElementById("scenario-content"); content.replaceChildren(); if (!rows().length) return content.appendChild(node("p", "most-scenario-empty", "Suas respostas aparecerão aqui conforme avançamos.")); rows().forEach(function (row) { var item = node("div", "most-scenario-item"); var copy = node("div"); copy.append(node("span", "", row[1]), node("strong", "", row[2])); item.append(copy, button("Editar", row[0], function () { edit(row[0]); }, true)); content.appendChild(item); }); }
  function review() { clearAction(); var card = node("div", "most-review-card"); card.appendChild(node("strong", "", "Resumo do seu cenário")); rows().forEach(function (row) { var item = node("div"); item.append(node("span", "", row[1]), node("b", "", row[2])); card.appendChild(item); }); var actions = node("div", "most-review-actions"); actions.append(button("Continuar", "continue", function () { answer("Continuar"); next(); }), button("Corrigir alguma informação", "edit", openPanel, true)); card.appendChild(actions); document.getElementById("conversation-action").appendChild(card); }
  function edit(state) { closePanel(); ask("Vamos ajustar essa informação."); app.current = state; var original = FLOW[state]; FLOW[state] = function () { FLOW[state] = original; app.results = simulateAllBanks(BANKS, scenario()); if (!document.getElementById("result").hidden) { renderResults(); return "scenario_exploration"; } return "scenario_review"; }; renderState(state); }

  function definition(list, label, value) { var item = node("div"); item.append(node("dt", "", label), node("dd", "", value)); list.appendChild(item); }
  function renderResults() { var valid = app.results.filter(function (item) { return item.status === "valid"; }); var best = valid.length ? valid.reduce(function (a, b) { return b.buyingPower > a.buyingPower ? b : a; }) : null; var result = document.getElementById("result"); result.hidden = false; document.getElementById("result-value").textContent = best ? money(best.buyingPower) : "Comparação bancária em configuração."; document.getElementById("result-copy").textContent = best ? "Estimativa baseada nas informações fornecidas e nos parâmetros utilizados nesta simulação." : "Seu cenário foi preenchido corretamente, mas os parâmetros bancários desta versão ainda estão em validação."; var summary = document.getElementById("result-summary"); summary.replaceChildren(); definition(summary, "Poder de compra estimado", best ? money(best.buyingPower) : "Em configuração"); definition(summary, "Entrada considerada", money(scenario().totalEntry)); definition(summary, "Capacidade máxima encontrada", best ? money(best.financingCapacity) : "Em configuração"); definition(summary, "Renda considerada", money(scenario().totalIncome)); highlights(valid); property(best); banks(); result.scrollIntoView({ behavior: "smooth", block: "start" }); }
  function highlights(valid) { var wrap = document.getElementById("result-highlights"); wrap.replaceChildren(); if (valid.length < 2) return; var picks = [["Maior capacidade estimada", valid.reduce(function (a, b) { return b.financingCapacity > a.financingCapacity ? b : a; }), "financingCapacity"], ["Menor primeira parcela", valid.reduce(function (a, b) { return b.firstPayment < a.firstPayment ? b : a; }), "firstPayment"], ["Maior prazo considerado", valid.reduce(function (a, b) { return b.termMonths > a.termMonths ? b : a; }), "termMonths"]]; picks.forEach(function (pick) { var card = node("article", "most-result-highlight"); card.append(node("span", "", pick[0]), node("strong", "", pick[1].bank.name), node("b", "", pick[2] === "termMonths" ? pick[1].termMonths + " meses" : money(pick[1][pick[2]]))); wrap.appendChild(card); }); }
  function property(best) { var wrap = document.getElementById("property-comparison"); wrap.replaceChildren(); if (!app.user.propertyValue) { wrap.hidden = true; return; } wrap.hidden = false; var power = best ? best.buyingPower : null; [["Seu poder de compra", power ? money(power) : "Em configuração"], ["Imóvel desejado", money(app.user.propertyValue)], ["Diferença", power ? money(Math.abs(power - app.user.propertyValue)) : "Em configuração"]].forEach(function (data) { var item = node("div"); item.append(node("span", "", data[0]), node("strong", "", data[1])); wrap.appendChild(item); }); wrap.appendChild(node("p", "", !power ? "A comparação depende de parâmetros bancários válidos." : power >= app.user.propertyValue ? "Seu cenário estimado alcança o valor informado." : "O imóvel informado está aproximadamente " + money(app.user.propertyValue - power) + " acima do seu poder de compra estimado.")); }
  function banks() { var grid = document.getElementById("bank-grid"); grid.replaceChildren(); document.getElementById("comparison-copy").textContent = app.results.some(function (item) { return item.status === "valid"; }) ? "Encontrei diferenças entre os cenários das instituições. Veja como cada uma se comportou:" : "Comparação bancária em configuração."; app.results.forEach(function (result) { var card = node("details", "most-bank-result"); var heading = node("summary"); heading.append(node("span", "", result.bank.name), node("small", "", result.status === "valid" ? "Cenário estimado" : result.message)); card.appendChild(heading); if (result.status !== "valid") card.appendChild(node("p", "most-bank-unavailable", result.message)); else { var list = node("dl"); [["Financiamento estimado", money(result.financingCapacity)], ["Poder de compra", money(result.buyingPower)], ["Primeira parcela", money(result.firstPayment)], ["Última parcela", money(result.lastPayment)], ["Renda necessária", money(result.requiredIncome)], ["Prazo", result.termMonths + " meses"], ["Taxa utilizada", PERCENT.format(result.bank.annualRate) + " a.a."], ["Sistema", result.bank.amortizationSystem], ["Data dos parâmetros", DATE.format(new Date(result.bank.sourceDate + "T00:00:00"))]].forEach(function (row) { definition(list, row[0], row[1]); }); card.appendChild(list); } grid.appendChild(card); }); }
  function exploration() { ask("Quer testar como seu cenário muda?"); replies([["Aumentar entrada", "entry"], ["Alterar renda", "income"], ["Testar outro imóvel", "property"], ["Nova simulação", "reset"]], function (value, label) { answer(label); if (value === "reset") return reset(); var config = value === "entry" ? ["Qual valor de entrada você quer testar?", "downPayment", true] : value === "income" ? ["Qual renda mensal você quer considerar nesse novo cenário?", "income", false] : ["Qual valor do imóvel você quer testar?", "propertyValue", false]; ask(config[0]); input({ label: config[0], placeholder: "R$ 0", mode: "numeric" }, function (raw) { var amount = parseMoney(raw); if ((!config[2] && amount <= 0) || amount > 999999999) return "Informe um valor válido."; app.user[config[1]] = amount; app.answered[config[1]] = true; if (config[1] === "propertyValue") app.user.goal = "property_check"; answer(money(amount)); updatePanel(); app.results = simulateAllBanks(BANKS, scenario()); renderResults(); ask(app.results.some(function (item) { return item.status === "valid"; }) ? "Atualizei seu cenário com o novo valor." : "Atualizei seu cenário. A comparação bancária continua em configuração."); exploration(); return ""; }); }); }
  function openPanel() { document.getElementById("scenario-panel").classList.add("is-open"); document.getElementById("scenario-toggle").setAttribute("aria-expanded", "true"); }
  function closePanel() { document.getElementById("scenario-panel").classList.remove("is-open"); document.getElementById("scenario-toggle").setAttribute("aria-expanded", "false"); }
  function reset() { app = createState(); document.getElementById("conversation-feed").replaceChildren(); document.getElementById("result").hidden = true; closePanel(); updatePanel(); go("welcome"); document.getElementById("most-simulator").scrollIntoView({ behavior: "smooth" }); }
  function setupHeader() { document.querySelectorAll("[data-bs-toggle='offcanvas']").forEach(function (trigger) { trigger.addEventListener("click", function () { var target = document.querySelector(trigger.getAttribute("data-bs-target")); setTimeout(function () { if (window.bootstrap && target && !target.classList.contains("show")) window.bootstrap.Offcanvas.getOrCreateInstance(target).show(); }, 80); }); }); }
  function init() { mount(); updatePanel(); document.getElementById("scenario-toggle").addEventListener("click", openPanel); document.getElementById("scenario-close").addEventListener("click", closePanel); setupHeader(); go("welcome"); }

  window.MostSimulatorEngine = { calculateAge: calculateAge, getAvailableTerm: getAvailableTerm, getIncomeCapacity: getIncomeCapacity, calculatePricePrincipal: calculatePricePrincipal, calculateSacPrincipal: calculateSacPrincipal, calculateFirstPayment: calculateFirstPayment, calculateLastPayment: calculateLastPayment, calculateRequiredIncome: calculateRequiredIncome, calculateBuyingPower: calculateBuyingPower, validateBankConfig: validateBankConfig, simulateBank: simulateBank, simulateAllBanks: simulateAllBanks };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
}());
